version: "3"

services: 
  nest_download:
    build: .
    container_name: nest_downloader
    volumes: 
      - ./download:/app
    environment: 
      - "NESTDOWNLOADER_PUBLIC_URL=https://video.nest.com/live/####" # from the nest share page
      - "NESTDOWNLOADER_SEGMENT_SIZE=300" #default
      - "NESTDOWNLOADER_FILENAME_FORMAT=%Y-%m-%d_%H-%M-%S-Garage.mp4" #default
      - "TZ=America/Los_Angeles"
